# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b53cdf2b72f8ed81414e9d2fc6ffc23dbc1da06bb2b7135e43e5bd915d2e4f888194919188ded76a22c66c75b4ec4a0e4933db401628894710461714a233e66a

test:
  secret_key_base: 965ac5dc7a51cb8fad44ce9550542f4573da4d92d54a6fe7047e7d0fcda6c43d5622033efb2e3b30308ab739f88dff55b62f991c2480a68828d1b3d43ff56a2c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
